
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:7 (PROJECT)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (PROJECT)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      .NET Framework 向け Microsoft (R) Build Engine バージョン 16.11.2+f32259642
      Copyright (C) Microsoft Corporation.All rights reserved.
      
      2025/06/15 11:52:18 にビルドを開始しました。
      ノード 1 上のプロジェクト "C:\\Users\\student\\Desktop\\bullet3\\build_x86\\CMakeFiles\\4.0.3\\CompilerIdC\\CompilerIdC.vcxproj" (既定のターゲット)。
      PrepareForBuild:
        ディレクトリ "Debug\\" を作成しています。
        ディレクトリ "Debug\\CompilerIdC.tlog\\" を作成しています。
      InitializeBuildStatus:
        "AlwaysCreate" が指定されたため "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" を作成しています。
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x86\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /external:W0 /Gd /TC /analyze- /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\student\\Desktop\\bullet3\\build_x86\\CMakeFiles\\4.0.3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x86\\cl.exe
      FinalizeBuildStatus:
        ファイル "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" を削除しています。
        "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate" のタッチ タスクを実行しています。
      プロジェクト "C:\\Users\\student\\Desktop\\bullet3\\build_x86\\CMakeFiles\\4.0.3\\CompilerIdC\\CompilerIdC.vcxproj" (既定のターゲット) のビルドが完了しました。
      
      ビルドに成功しました。
          0 個の警告
          0 エラー
      
      経過時間 00:00:00.64
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/student/Desktop/bullet3/build_x86/CMakeFiles/4.0.3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (PROJECT)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      .NET Framework 向け Microsoft (R) Build Engine バージョン 16.11.2+f32259642
      Copyright (C) Microsoft Corporation.All rights reserved.
      
      2025/06/15 11:52:18 にビルドを開始しました。
      ノード 1 上のプロジェクト "C:\\Users\\student\\Desktop\\bullet3\\build_x86\\CMakeFiles\\4.0.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (既定のターゲット)。
      PrepareForBuild:
        ディレクトリ "Debug\\" を作成しています。
        ディレクトリ "Debug\\CompilerIdCXX.tlog\\" を作成しています。
      InitializeBuildStatus:
        "AlwaysCreate" が指定されたため "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" を作成しています。
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x86\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /external:W0 /Gd /TP /analyze- /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\student\\Desktop\\bullet3\\build_x86\\CMakeFiles\\4.0.3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x86\\cl.exe
      FinalizeBuildStatus:
        ファイル "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" を削除しています。
        "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate" のタッチ タスクを実行しています。
      プロジェクト "C:\\Users\\student\\Desktop\\bullet3\\build_x86\\CMakeFiles\\4.0.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (既定のターゲット) のビルドが完了しました。
      
      ビルドに成功しました。
          0 個の警告
          0 エラー
      
      経過時間 00:00:00.48
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/student/Desktop/bullet3/build_x86/CMakeFiles/4.0.3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:83 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:7 (PROJECT)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/student/Desktop/bullet3/build_x86/CMakeFiles/CMakeScratch/TryCompile-76pq4p"
      binary: "C:/Users/student/Desktop/bullet3/build_x86/CMakeFiles/CMakeScratch/TryCompile-76pq4p"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/student/Desktop/bullet3/build_x86/CMakeFiles/CMakeScratch/TryCompile-76pq4p'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" cmTC_3bc00.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=16.0 /v:n
        .NET Framework 向け Microsoft (R) Build Engine バージョン 16.11.2+f32259642
        Copyright (C) Microsoft Corporation.All rights reserved.
        
        2025/06/15 11:52:19 にビルドを開始しました。
        ノード 1 上のプロジェクト "C:\\Users\\student\\Desktop\\bullet3\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-76pq4p\\cmTC_3bc00.vcxproj" (既定のターゲット)。
        PrepareForBuild:
          ディレクトリ "cmTC_3bc00.dir\\Debug\\" を作成しています。
          ディレクトリ "C:\\Users\\student\\Desktop\\bullet3\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-76pq4p\\Debug\\" を作成しています。
          ディレクトリ "cmTC_3bc00.dir\\Debug\\cmTC_3bc00.tlog\\" を作成しています。
        InitializeBuildStatus:
          "AlwaysCreate" が指定されたため "cmTC_3bc00.dir\\Debug\\cmTC_3bc00.tlog\\unsuccessfulbuild" を作成しています。
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x86\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_3bc00.dir\\Debug\\\\" /Fd"cmTC_3bc00.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TC /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-4.0\\Modules\\CMakeCCompilerABI.c"
          Microsoft(R) C/C++ Optimizing Compiler Version 19.29.30159 for x86
          Copyright (C) Microsoft Corporation.  All rights reserved.
          CMakeCCompilerABI.c
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_3bc00.dir\\Debug\\\\" /Fd"cmTC_3bc00.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TC /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-4.0\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\student\\Desktop\\bullet3\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-76pq4p\\Debug\\cmTC_3bc00.exe" /INCREMENTAL /ILK:"cmTC_3bc00.dir\\Debug\\cmTC_3bc00.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/student/Desktop/bullet3/build_x86/CMakeFiles/CMakeScratch/TryCompile-76pq4p/Debug/cmTC_3bc00.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/student/Desktop/bullet3/build_x86/CMakeFiles/CMakeScratch/TryCompile-76pq4p/Debug/cmTC_3bc00.lib" /MACHINE:X86  /machine:X86 cmTC_3bc00.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_3bc00.vcxproj -> C:\\Users\\student\\Desktop\\bullet3\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-76pq4p\\Debug\\cmTC_3bc00.exe
        FinalizeBuildStatus:
          ファイル "cmTC_3bc00.dir\\Debug\\cmTC_3bc00.tlog\\unsuccessfulbuild" を削除しています。
          "cmTC_3bc00.dir\\Debug\\cmTC_3bc00.tlog\\cmTC_3bc00.lastbuildstate" のタッチ タスクを実行しています。
        プロジェクト "C:\\Users\\student\\Desktop\\bullet3\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-76pq4p\\cmTC_3bc00.vcxproj" (既定のターゲット) のビルドが完了しました。
        
        ビルドに成功しました。
            0 個の警告
            0 エラー
        
        経過時間 00:00:00.48
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:227 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:7 (PROJECT)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'C': C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/HostX64/x86/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CMakeDetermineLinkerId.cmake:36 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:270 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:7 (PROJECT)"
    message: |
      Running the C compiler's linker: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/HostX64/x86/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.29.30159.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:83 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:7 (PROJECT)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/student/Desktop/bullet3/build_x86/CMakeFiles/CMakeScratch/TryCompile-gamaey"
      binary: "C:/Users/student/Desktop/bullet3/build_x86/CMakeFiles/CMakeScratch/TryCompile-gamaey"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/student/Desktop/bullet3/build_x86/CMakeFiles/CMakeScratch/TryCompile-gamaey'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" cmTC_0c383.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=16.0 /v:n
        .NET Framework 向け Microsoft (R) Build Engine バージョン 16.11.2+f32259642
        Copyright (C) Microsoft Corporation.All rights reserved.
        
        2025/06/15 11:52:20 にビルドを開始しました。
        ノード 1 上のプロジェクト "C:\\Users\\student\\Desktop\\bullet3\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-gamaey\\cmTC_0c383.vcxproj" (既定のターゲット)。
        PrepareForBuild:
          ディレクトリ "cmTC_0c383.dir\\Debug\\" を作成しています。
          ディレクトリ "C:\\Users\\student\\Desktop\\bullet3\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-gamaey\\Debug\\" を作成しています。
          ディレクトリ "cmTC_0c383.dir\\Debug\\cmTC_0c383.tlog\\" を作成しています。
        InitializeBuildStatus:
          "AlwaysCreate" が指定されたため "cmTC_0c383.dir\\Debug\\cmTC_0c383.tlog\\unsuccessfulbuild" を作成しています。
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x86\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_0c383.dir\\Debug\\\\" /Fd"cmTC_0c383.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TP /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-4.0\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft(R) C/C++ Optimizing Compiler Version 19.29.30159 for x86
          Copyright (C) Microsoft Corporation.  All rights reserved.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_0c383.dir\\Debug\\\\" /Fd"cmTC_0c383.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TP /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-4.0\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\student\\Desktop\\bullet3\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-gamaey\\Debug\\cmTC_0c383.exe" /INCREMENTAL /ILK:"cmTC_0c383.dir\\Debug\\cmTC_0c383.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/student/Desktop/bullet3/build_x86/CMakeFiles/CMakeScratch/TryCompile-gamaey/Debug/cmTC_0c383.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/student/Desktop/bullet3/build_x86/CMakeFiles/CMakeScratch/TryCompile-gamaey/Debug/cmTC_0c383.lib" /MACHINE:X86  /machine:X86 cmTC_0c383.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_0c383.vcxproj -> C:\\Users\\student\\Desktop\\bullet3\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-gamaey\\Debug\\cmTC_0c383.exe
        FinalizeBuildStatus:
          ファイル "cmTC_0c383.dir\\Debug\\cmTC_0c383.tlog\\unsuccessfulbuild" を削除しています。
          "cmTC_0c383.dir\\Debug\\cmTC_0c383.tlog\\cmTC_0c383.lastbuildstate" のタッチ タスクを実行しています。
        プロジェクト "C:\\Users\\student\\Desktop\\bullet3\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-gamaey\\cmTC_0c383.vcxproj" (既定のターゲット) のビルドが完了しました。
        
        ビルドに成功しました。
            0 個の警告
            0 エラー
        
        経過時間 00:00:00.46
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:227 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:7 (PROJECT)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'CXX': C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/HostX64/x86/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CMakeDetermineLinkerId.cmake:36 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:270 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:7 (PROJECT)"
    message: |
      Running the CXX compiler's linker: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/HostX64/x86/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.29.30159.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
